apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cloudshells.cloudshell.eclipse.org
spec:
  group: cloudshell.eclipse.org
  names:
    kind: CloudShell
    listKind: CloudShellList
    plural: cloudshells
    singular: cloudshell
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CloudShell is the Schema for the cloudshells API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CloudShellSpec defines the desired state of CloudShell
          properties:
            image:
              type: string
          required:
          - image
          type: object
        status:
          description: CloudShellStatus defines the observed state of CloudShell
          properties:
            id:
              type: string
            ready:
              type: boolean
            url:
              type: string
          required:
          - id
          - ready
          - url
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
